version: '3'
services:
  personal:
    container_name: flask_personal
    # Mounts to current directory so that live-reloads can be seen
    volumes:
      - ./src:/usr/src
    command: ash -c "
      export FLASK_ENV=development &&
      gunicorn -w 2 -b 0.0.0.0:5000 'app:create_app()' "

  live-reloader:
    image: apogiatzis/livereloading
    container_name: livereloader
    privileged: true
    environment:
      - RELOAD_DELAY=1.5              # seconds
      - RELOAD_CONTAINER=flask_personal
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./src:/usr/src