name: Publish Docker Image

on:
  pull_request:
    types: [ opened, edited, synchronize ]
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  docker-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2
      - name: Build and Publish latest Docker Image
        uses: VaultVulp/gp-docker-actions@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: flask-personal
          dockerfile: src/Dockerfile