# Trigger deploy
name: Publish Docker Image

on:
  pull_request:
    types: [edited]
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  docker-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t frontend-flask:latest src/ &&
      - name: Authenticate - Tag - Publish
        run: |
          docker login docker.pgk.github.com -u ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }} &&
          docker tag frontend-flask:latest docker.pkg.github.com/brainabar/frontend-flask/frontend-flask:latest &&
          docker push docker.pkg.github.com/brainabar/frontend-flask/frontend-flask:latest
