name: Publish Docker Image

on:
  pull_request:
    types: [ opened, edited, synchronize ]
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  docker-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t frontend-flask:latest src/
      - name: Authenticate
        run: |
          docker login docker.pgk.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
      - name: Tag
        run: |
          docker tag frontend-flask:latest docker.pkg.github.com/brainabar/frontend-flask/frontend-flask:latest
      - name: Publish
        run: |
          docker push docker.pkg.github.com/brainabar/frontend-flask/frontend-flask:latest
