# Trigger deploy
name: Publish Docker Image

on:
  pull_request:
    types: [closed]
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `latest` tags as releases.
    tags:
      - latest

jobs:
  docker-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2
      - name: Push to Github Packages
        uses: docker/build-push-actions@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: BrainABar/Frontend-Flask
          tag_with_ref: true
          push: true
