name: Publish Docker Image

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `latest` tags as releases.
    tags:
      - latest

jobs:
  docker-package:
    if: github.event.pull_request.merged == 'true'
      runs-on: ubuntu-latest
      steps:
        - name: Check out Repo
          uses: actions/checkout@v2
        - name: Push to Github Packages
          uses: docker/build-push-actions@v1
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: BrainABar/Frontend-Flask
            tag_with_ref: true
            push: true